const livros = [
    {
        id: 1,
        nome: 'As crônicas de Nárnia',
        autor: 'CS Lewis',
        categoria: 'Aventura',
        paginas: 752,
        recomenda: true,
        leu: true,
    },
    {
        id: 2,
        nome: 'O Hobbit',
        autor: 'JRR Tolkien',
        categoria: 'Aventura',
        paginas: 336,
        recomenda: false,
        leu: false,
    },
    {
        id: 3,
        nome: 'A coisa',
        autor: 'Stephen King',
        categoria: 'Aventura',
        paginas: 1104,
        recomenda: false,
        leu: false,
    },
    {
        id: 4,
        nome: 'O mito da caverna',
        autor: 'Platão',
        categoria: 'Filosofia',
        paginas: 80,
        recomenda: true,
        leu: true,
    },
    {
        id: 5,
        nome: 'O príncipe',
        autor: 'Maquiavel',
        categoria: 'Filosofia',
        paginas: 96,
        recomenda: true,
        leu: true,
    },
    {
        id: 6,
        nome: 'O contrato social',
        autor: 'JJ Rousseau',
        categoria: 'Filosofia',
        paginas: 128,
        recomenda: true,
        leu: true,
    },
    {
        id: 7,
        nome: 'As seis lições',
        autor: 'LV Mises',
        categoria: 'Economia',
        paginas: 184,
        recomenda: true,
        leu: true,
    },
    {
        id: 8,
        nome: 'Introdução à programação com Python',
        autor: 'NNC Menezes',
        categoria: 'Programação',
        paginas: 328,
        recomenda: false,
        leu: false,
    }
]

module.exports = livros;